# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Habib Ahmed Bhutto
email: habibbhutto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some words about the stuff I do like this and that. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://habibbhutto.github.io/" # the base hostname & protocol for your site
twitter_username: BhuttoHabib
github_username:  habibbhutto

# Build settings
markdown: kramdown
